services:
  db:
    image: mariadb:11
    container_name: tortoise-wow-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mangos
      MYSQL_PASSWORD: mangos
    volumes:
      - ${TORTOISE_DATA_DIR:-./data}/mysql:/var/lib/mysql
      - ${TORTOISE_DATA_DIR:-./data}/mysql/init:/docker-entrypoint-initdb.d:ro
      - ./sql/:/sql_imports/
    networks:
      - tortoise-wow-net
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  realmd:
    image: ghcr.io/faemwow/tortoise-wow-realmd:latest
    container_name: tortoise-wow-realmd
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${TORTOISE_DATA_DIR:-./data}/etc/realmd.conf:/etc/realmd.conf:ro
    ports:
      - "3724:3724"
    networks:
      - tortoise-wow-net
  mangosd:
    image: ghcr.io/faemwow/tortoise-wow-mangosd:latest
    container_name: tortoise-wow-mangosd
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${TORTOISE_DATA_DIR:-./data}/etc/mangosd.conf:/etc/mangosd.conf:ro
      - ${TORTOISE_DATA_DIR:-./data}/dbc:/tortoise/data/dbc:ro
      - ${TORTOISE_DATA_DIR:-./data}/maps:/tortoise/data/maps:ro
      - ${TORTOISE_DATA_DIR:-./data}/vmaps:/tortoise/data/vmaps:ro
      - ${TORTOISE_DATA_DIR:-./data}/mmaps:/tortoise/data/mmaps:ro
      - ${TORTOISE_DATA_DIR:-./sql}:/tortoise/sql:ro #sql files from repo
      - ./sql/unused:/tortoise/sql/unused #db_autoupdate needs this
    ports:
      - "8085:8085"
    networks:
      - tortoise-wow-net
    stdin_open: true
    tty: true

networks:
  tortoise-wow-net:
    driver: bridge
