services:
  db:
    image: tortoise-wow-db:latest
    volumes:
      - ./tortoise-files/db-data:/var/lib/mysql

  realmd:
    image: tortoise-wow-realmd:latest
    volumes:
      - ./tortoise-files/etc/realmd.conf:/etc/realmd.conf
    depends_on:
      - db
    ports:
      - "3724:3724"
    restart: on-failure

  mangosd:
    image: tortoise-wow-mangosd:latest
    volumes:
      - ./tortoise-files/etc/mangosd.conf:/etc/mangosd.conf
      - ./tortoise-files:/tortoise
    depends_on:
      - db
    ports:
      - "8091:8091"
    tty: true
    stdin_open: true
    restart: on-failure
